language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="mirage-clock:. mirage-clock-unix:. mirage-clock-freestanding:. mirage-clock-lwt:."
  - DISTRO="debian-stable"
  matrix:
  - PACKAGE="mirage-clock" OCAML_VERSION="4.04.2"
  - PACKAGE="mirage-clock" OCAML_VERSION="4.05.0"
  - PACKAGE="mirage-clock" OCAML_VERSION="4.06.0"
  - PACKAGE="mirage-clock-unix" OCAML_VERSION="4.04.2"
  - PACKAGE="mirage-clock-unix" OCAML_VERSION="4.05.0"
  - PACKAGE="mirage-clock-unix" OCAML_VERSION="4.06.0"
  - PACKAGE="mirage-clock-freestanding" OCAML_VERSION="4.04.2"
  - PACKAGE="mirage-clock-freestanding" OCAML_VERSION="4.05.0"
  - PACKAGE="mirage-clock-freestanding" OCAML_VERSION="4.06.0"
  - PACKAGE="mirage-clock-lwt" OCAML_VERSION="4.04.2"
  - PACKAGE="mirage-clock-lwt" OCAML_VERSION="4.05.0"
  - PACKAGE="mirage-clock-lwt" OCAML_VERSION="4.06.0"
